api_platform:
    title: 'Job Contact API'
    version: '2.0.0'
    show_webby: true
    name_converter: 'Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter'
    mapping:
        paths:
            - '%kernel.project_dir%/config/api_platform'
