api_platform:
    title: 'Job Contact API'
    version: '2.5.1'
    name_converter: 'Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter'
    mapping:
        paths:
            - '%kernel.project_dir%/config/api_platform'
