framework:
    serializer:
        mapping:
            paths:
                - '%kernel.project_dir%/config/serialization'

    secret: '%env(APP_SECRET)%'
    session:
        handler_id: ~
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true
    php_errors:
        log: true
