version: "3.2"
services:

  mysql:
    image: mysql:8.0
    env_file: .env
    volumes:
      - mysql:/var/lib/mysql
      - ./docker/data:/docker/data
      - ./docker/mysql:/etc/mysql/conf.d

  php:
    build: ./docker/php
    env_file: .env
    environment:
      SSH_AUTH_SOCK: /tmp/agent.sock
    volumes:
      - $SSH_AUTH_SOCK:/tmp/agent.sock
      - ~/.composer:/home/.composer
      - ./docker/config/bashrc:/home/.bashrc
      - ./docker/config/bash_aliases:/home/.bash_aliases
      - ./docker/config/inputrc:/home/.inputrc
      - ./docker/data/history:/home/.bash_history
      - ./:/srv/

  nginx:
    image: nginx:1.15.9-alpine
    expose:
      - 443
    depends_on:
      - php
    volumes:
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/srv/:ro

volumes:
  mysql: ~
