version: "3.2"
services:

  mysql:
    image: mysql:8.0
    container_name: typeform-mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=jobcontact
      - MYSQL_ROOT_PASSWORD=jobcontact
      - MYSQL_USER=jobcontact
      - MYSQL_PASSWORD=jobcontact
    volumes:
      - mysql:/var/lib/mysql
      - ./docker/data:/docker/data

  php:
    build: ./docker/php
    env_file: docker.env
    container_name: typeform-php
    volumes:
      - $SSH_AUTH_SOCK:/tmp/agent.sock
      - ~/.composer:/home/.composer
      - ./docker/config/bashrc:/home/.bashrc
      - ./docker/config/bash_aliases:/home/.bash_aliases
      - ./docker/data/history:/home/.bash_history
      - ./:/srv/

  nginx:
    image: nginx:1.15.9-alpine
    container_name: typeform-nginx
    expose:
      - 443
    depends_on:
      - php
    volumes:
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/certs:/etc/nginx/certs
      - ./:/srv/:ro

volumes:
  mysql: ~
