App\Entity\Anwser:
  attributes:
    normalization_context:
      groups: ['read']
    denormalization_context:
      groups: ['write']
    id:
      groups: ['read']
    question:
      groups: ['write', 'read']