App\Entity\Question:
  attributes:
    normalization_context:
      groups: ['read']
    denormalization_context:
      groups: ['write']
    id:
      groups: ['read']
    label:
      groups: ['read', 'write']