App\Dto\TypeformAnswerPayload:
  properties:
    formResponse:
      - Type: array
      - NotBlank: ~
      - NotNull: ~
    eventType:
      - Type: string
      - EqualTo: form_response
      - NotBlank: ~
      - NotNull: ~
    eventId:
      - Type: string
      - NotBlank: ~
      - NotNull: ~
      
