name: Main CI
on:
  push:
    branches-ignore:
      - master

jobs:
  quality-ci:
    name: Quality CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: PHP CS Fixer
        id: php-cs-fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --verbose --diff --dry-run
      - name: Install Dependancies
        if: ${{ success() }}
        uses: mihani/docker-image-typeform-api-php@v2
        with:
          args: composer install --prefer-dist --no-progress
      - name: PHP Unit test
        if: ${{ success() }}
        run: php bin/phpunit
